<%
  etcd_machines = nil
  if_p("etcd.machines") do |machines|
    etcd_machines = machines
  end
  unless etcd_machines
    etcd_machines = link("etcd").instances.map(&:address)
  end
-%>
backend = "etcd"
nodes = <%= etcd_machines.map {|h| "#{h}:4001"} %>
scheme = "http"
prefix = "/"
watch = true

interval = 15
debug = false
verbose = true
quiet = true
