---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci

params:
  router_ip: 10.58.111.47

run:
  path: boshrelease-ci/ci/tasks/assert-disaster-recovery.sh
