---
platform: linux
image: docker:///dingotiles/patroni-docker-boshrelease-pipeline

inputs:
- name: boshrelease
- name: boshrelease-ci
- name: edge-image
  path: images/cfcommunity_postgresql_patroni_9_5_image
- name: docker-image-registrator
  path: images/cfcommunity_registrator_latest_image

outputs:
- name: boshrelease-images-updated

params:
  aws_access_key_id:
  aws_secret_access_key:

run:
  path: boshrelease-ci/ci/tasks/bump-image-layers.sh
