---
platform: linux
image: docker:///dingotiles/patroni-docker-boshrelease-pipeline

inputs:
- {name: boshrelease-ci}
- {name: boshrelease}
- {name: version}
- name: edge-image
  path: images/cfcommunity_postgresql_patroni_9_5_image
- name: docker-image-registrator
  path: images/cfcommunity_registrator_latest_image

outputs:
- {name: candidate-release}

params:
  aws_access_key_id:
  aws_secret_access_key:

run:
  path: ./boshrelease-ci/ci/tasks/create-candidate-release.sh
