---
platform: linux

image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci

outputs:
- name: director-state

params:
  GITHUB_TOKEN:
  VAULT_PREFIX:
  VAULT_ADDR:
  VAULT_SKIP_VERIFY: 1

run:
  path: boshrelease-ci/ci/tasks/director-creds.sh
