---
platform: linux
image: docker:///dingotiles/patroni-docker-boshrelease-pipeline

inputs:
- name: boshrelease
- name: boshrelease-ci
- name: candidate-release
- name: version

outputs:
- name: final-release-repo
- name: final-release-tarball

params:
  aws_access_key_id:
  aws_secret_access_key:

run:
  path: ./boshrelease-ci/ci/tasks/finalize-release.sh
