---
platform: linux
image_resource:
  type: docker-image
  source: {repository: ruby, tag: '2.2-slim' }

inputs:
- name: boshrelease
- name: boshrelease-ci
- name: version

outputs:
- name: license-finder-reports

run:
  path: ./boshrelease-ci/ci/tasks/license-finder-report.sh
