---
platform: linux
image: docker:///dingotiles/patroni-docker-boshrelease-pipeline

inputs:
- {name: boshrelease-ci}
- {name: boshrelease}
- {name: patroni}

outputs:
- {name: dockerfile}

params:
  dockerfile_root:

run:
  path: ./boshrelease-ci/ci/tasks/prepare-dockerfile.sh
