---
platform: linux
image_resource:
  type: docker-image
  source: { repository: bodymindarts/delmo-concourse }

inputs:
- name: boshrelease-ci

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_BUCKET:
  MACHINE_NAME: dingo-postgresql-pipeline

run:
  path: /entrypoint.sh
  args: [delmo, --only-build-task, -f, boshrelease-ci/images/delmo.yml, -m, dingo-postgresql-pipeline]
