---
platform: linux
image: docker:///dingotiles/patroni-docker-boshrelease-pipeline

inputs:
- {name: boshrelease-ci}
- {name: boshrelease}
- {name: version}

outputs:
- {name: vsphere-manifest}

params:
  aws_access_key:
  aws_secret_key:
  s3_bucket:
  s3_endpoint:

run:
  path: ./boshrelease-ci/ci/tasks/setup-vsphere-manifest.sh
