---
platform: linux
image: docker:///dingotiles/patroni-docker-boshrelease-pipeline

inputs:
- name: boshrelease

params:
  bosh_target:
  bosh_username: admin
  bosh_password: admin

run:
  path: boshrelease/ci/tasks/upload-dev-release.sh
