meta:
  persistent_disk: 40960

  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: patroni
    networks:
      - name: patroni1
    persistent_disk: (( grab meta.persistent_disk ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: cell_z1
    cloud_properties:
      instance_type: m1.small

networks:
- name: patroni1
  type: manual
  subnets: (( merge ))
