meta:
  persistent_disk: 40960

  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: cell_z1
    networks: [{name: patroni1}]
    persistent_disk: (( grab meta.persistent_disk ))
  - name: broker
    networks:
      - name: router1
        static_ips: (( static_ips(2,3) ))
  - name: router
    networks:
      - name: router1
        static_ips: (( static_ips(0,1) ))

compilation:
  cloud_properties: {instance_type: m1.small}

resource_pools:
  - name: cell_z1
    cloud_properties: {instance_type: c4.medium}
  - name: broker_z1
    cloud_properties: {instance_type: t2.small}
  - name: router_z1
    cloud_properties: {instance_type: t2.small}

networks:
- name: patroni1
  type: manual
  subnets: (( param "please provide subnets for patroni cells" ))
- name: router1
  type: manual
  subnets: (( param "please provide subnets for router/brokers" ))
