meta:
  subnets: (( merge ))
  cfcontainersbroker:
    cc_api_uri: "https://api.10.244.0.34.xip.io"
    external_host: "cf-containers-broker.10.244.0.34.xip.io"
  nats:
    user: nats
    password: nats
    port: 4222
    machines:
      - 10.244.0.6

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  etcd:
    host: 10.244.4.2

jobs:
  - name: cell_z1
    networks: [{name: patroni1}]
  - name: broker
    networks:
      - name: router1
        static_ips: (( static_ips(2,3) ))
  - name: router
    networks:
      - name: router1
        static_ips: (( static_ips(0,1) ))

compilation:
  cloud_properties: {name: random}

resource_pools:
  - name: cell_z1
    cloud_properties: {name: random}
  - name: broker_z1
    cloud_properties: {name: random}
  - name: router_z1
    cloud_properties: {name: random}

networks:
- name: patroni1
  type: manual
  subnets:
  - range: 10.244.21.0/24
    gateway: 10.244.21.1
    static: [10.244.21.2-10.244.21.6]

- name: router1
  type: manual
  subnets:
  - range: 10.244.21.0/24
    gateway: 10.244.21.1
    static: [10.244.21.2-10.244.21.6]
