meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  etcd:
    host: 10.244.4.2

jobs:
  - name: cell_z1
    networks:
      - name: patroni1
        static_ips: (( static_ips(5,6,7,8) ))
  - name: broker
    networks:
      - name: router1
        static_ips: (( static_ips(2,3) ))
    properties:
      broker:
        router:
          hostname: (( grab jobs.router.networks.router1.static_ips.[0] ))
        backends:
          machines: (( grab jobs.cell_z1.networks.patroni1.static_ips ))
  - name: router
    networks:
      - name: router1
        static_ips: (( static_ips(0,1) ))

compilation:
  cloud_properties: {name: random}

resource_pools:
  - name: cell_z1
    cloud_properties: {name: random}
  - name: broker_z1
    cloud_properties: {name: random}
  - name: router_z1
    cloud_properties: {name: random}

networks:
- name: patroni1
  type: manual
  subnets:
  - range: 10.244.21.0/24
    gateway: 10.244.21.1
    static: [10.244.21.2-10.244.21.20]

- name: router1
  type: manual
  subnets:
  - range: 10.244.21.0/24
    gateway: 10.244.21.1
    static: [10.244.21.2-10.244.21.20]
