meta:
  persistent_disk: 40960

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: cell_z1
    instances: 1
    networks:
      - name: patroni1
        static_ips: (( static_ips(5,6,7,8,9,10,11) ))
    persistent_disk: (( grab meta.persistent_disk ))
  - name: cell_z2
    instances: 1
    networks:
      - name: patroni2
        static_ips: (( static_ips(0,1,2,3,4,5,6) ))
    persistent_disk: (( grab meta.persistent_disk ))
  - name: broker
    networks:
      - name: router1
        static_ips: (( static_ips(2,3) ))
    properties:
      servicebroker:
        router:
          hostname: (( grab jobs.router.networks.router1.static_ips.[0] ))
        backends:
            z1: (( grab jobs.cell_z1.networks.patroni1.static_ips ))
            z2: (( grab jobs.cell_z2.networks.patroni2.static_ips ))
  - name: router
    networks:
      - name: router1
        static_ips: (( static_ips(0,1) ))
    properties:
      servicebroker:
        machines: (( grab jobs.broker.networks.router1.static_ips ))
  - name: sanity-test
    properties:
      servicebroker:
        machines: (( grab jobs.broker.networks.router1.static_ips ))

compilation:
  cloud_properties: {instance_type: c3.large}

resource_pools:
  - name: cell_z1
    cloud_properties: {instance_type: c3.large}
  - name: cell_z2
    cloud_properties: {instance_type: c3.large}
  - name: broker_z1
    cloud_properties: {instance_type: t2.small}
  - name: router_z1
    cloud_properties: {instance_type: t2.small}

networks:
- name: patroni1
  type: manual
  subnets: (( param "please provide subnets for patroni cells" ))
- name: patroni2
  type: manual
  subnets: (( param "please provide subnets for patroni cells" ))
- name: router1
  type: manual
  subnets: (( param "please provide subnets for router/brokers" ))
