meta:
  job_templates:
    patroni: (( param "please provide templates for cells" ))

releases:
- name: patroni
  version: latest
- name: logsearch-shipper
  version: latest

jobs:
  - name: cell_z1
    instances: 3
    templates: (( grab meta.job_templates.patroni ))
    resource_pool: cell_z1
    networks: [{name: patroni1}]
    persistent_disk: 10240
    properties:
      zone: z1
  - name: cell_z2
    instances: 3
    templates: (( grab meta.job_templates.patroni ))
    resource_pool: cell_z2
    networks: [{name: patroni2}]
    persistent_disk: 10240
    properties:
      zone: z2
  - name: router
    instances: 1
    templates:
      - {name: logsearch-shipper, release: logsearch-shipper}
      - {name: router, release: patroni}
    resource_pool: router_z1
    networks: [{name: router1}]
  - name: broker
    instances: 1
    templates:
      - {name: logsearch-shipper, release: logsearch-shipper}
      - {name: broker, release: patroni}
    resource_pool: broker_z1
    networks: [{name: router1}]
    properties:
      servicebroker:
        router:
          hostname: (( param "please provide public hostname for routers" ))
        backends:
          machines:
            z1: (( param "please provide array of z1 service broker hostnames/ips" ))
            z2: (( param "please provide array of z2 service broker hostnames/ips" ))
    update:
      canary_watch_time: 10000-30000
      update_watch_time: 10000-30000
  - name: sanity-test
    instances: 1
    lifecycle: errand
    templates: [{name: sanity-test, release: patroni}]
    resource_pool: router_z1
    networks: [{name: router1}]

resource_pools:
  - name: cell_z1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please provide cloud_properties"))
    network: patroni1
  - name: cell_z2
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please provide cloud_properties"))
    network: patroni2
  - name: router_z1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please provide cloud_properties"))
    network: router1
  - name: broker_z1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please provide cloud_properties"))
    network: router1

networks:
- name: patroni1
- name: patroni2
- name: router1

properties:
  servicebroker:
    port: 8888
    username: starkandwayne
    password: starkandwayne
  etcd:
    machines: (( param "please provide array of etcd hostnames" ))
  logsearch:
    logs:
      enabled: false
      server: "dummy:514"
