update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: patroni
    instances: 3
    templates: (( grab meta.job_templates ))
    resource_pool: cell_z1
    networks: (( merge ))
    persistent_disk: 10240

networks: (( param "please provide networks" ))
