---
groups:
- name: pipeline
  jobs: [image-patroni-pg95, testflight, shipit]
- name: base
  jobs: [image-patroni-pg95-base, build-task-image]

jobs:
- name: image-patroni-pg95-base
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease}
    - {get: boshrelease-pg95-base-image, trigger: true, params: {submodules: none}}
  - put: docker-image-pg95-patroni-base
    params:
      build: boshrelease/images/postgresql95-patroni-base

- name: image-patroni-pg95
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: patroni, resource: patched-patroni, trigger: true}
    - {get: boshrelease}
    - {get: docker-image-pg95-patroni-base, trigger: true}
    - {get: boshrelease-pg95-image, trigger: true, params: {submodules: none}}
  - task: prepare-dockerfile
    file: boshrelease/ci/tasks/prepare-dockerfile.yml
    config:
      params:
        dockerfile_root: boshrelease/images/postgresql95-patroni
  - put: docker-image-pg95-patroni
    params:
      build: dockerfile

- name: testflight
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease}
    - {get: boshrelease-ci}
    - {get: docker-image-pg95-patroni, passed: [image-patroni-pg95], trigger: true}
  - task: upload-dev-release
    file: boshrelease-ci/ci/tasks/upload-dev-release.yml
    config:
      params:
        bosh_target: {{bosh-lite-target}}
        bosh_username: {{bosh-lite-username}}
        bosh_password: {{bosh-lite-password}}
        bosh_syslog_host: {{bosh-lite-syslog-host}}
        bosh_syslog_port: {{bosh-lite-syslog-port}}

- name: shipit
  public: true
  plan:
    - {get: boshrelease, passed: [testflight]}
    - {get: boshrelease-ci}
    - {get: version}

- name: build-task-image
  serial: true
  plan:
  - {get: boshrelease-ci-task, trigger: true}
  - put: docker-image-ci
    params:
      build: boshrelease-ci-task/ci/ci_image

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: boshrelease-ci
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: boshrelease-ci-task
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [ci/ci_image/*]

- name: boshrelease-pg95-image
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [images/postgresql95-patroni]

- name: boshrelease-pg95-base-image
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [images/postgresql95-patroni-base]

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: version
    file: version
    private_key: {{github-private-key}}

- name: patched-patroni
  type: git
  source:
    uri: https://github.com/drnic/patroni.git
    branch: connect_address
    # uri: https://github.com/zalando/patroni.git
    # branch: master
    private_key: {{github-private-key}}

- name: docker-image-pg95-patroni-base
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql-patroni-base
    tag: "9.5"

- name: docker-image-pg95-patroni
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql-patroni
    tag: "9.5"

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/patroni-docker-boshrelease-pipeline
