---
groups:
- name: pipeline
  jobs: [bosh-rc, testflight, shipit, rc]
- name: versions
  jobs: [minor, major, patch]
- name: images
  jobs: [image-patroni-pg95, image-patroni-pg95-base, build-task-image]

jobs:
- name: image-patroni-pg95-base
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease}
    - {get: boshrelease-pg95-base-image, trigger: true, params: {submodules: none}}
  - put: docker-image-pg95-patroni-base
    params:
      build: boshrelease/images/postgresql95-patroni-base

- name: image-patroni-pg95
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease-ci}
    - {get: boshrelease, resource: boshrelease-pg95-image, trigger: true, params: {submodules: none}}
    - {get: patroni, resource: patched-patroni, trigger: true}
    - {get: docker-image-pg95-patroni-base, trigger: true}
  - task: prepare-dockerfile
    file: boshrelease-ci/ci/tasks/prepare-dockerfile.yml
    config:
      params:
        dockerfile_root: boshrelease/images/postgresql95-patroni
  - put: docker-image-pg95-patroni
    params:
      build: dockerfile

- name: bosh-rc
  public: true
  plan:
  - aggregate:
    - {get: boshrelease-ci}
    - {get: boshrelease, passed: [rc], trigger: true}
    - {get: version, passed: [rc], trigger: true}
  - task: create-candidate-release
    file: boshrelease-ci/ci/tasks/create-candidate-release.yml
    config:
      params:
        aws_access_key_id: {{dingotiles-aws-access}}
        aws_secret_access_key: {{dingotiles-aws-secret}}
  - put: candidate-release
    params: {file: candidate-release/patroni-docker-*.tgz}

- name: testflight
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease, passed: [bosh-rc]}
    - {get: version, passed: [bosh-rc]}
    - {get: candidate-release, passed: [bosh-rc]}
    - {get: boshrelease-ci}
    - {get: etcd}
    - {get: remote-syslog}
  - task: create-lite-manifest
    file: boshrelease-ci/ci/tasks/create-manifest.yml
    config:
      params:
        deployment_name: patroni-docker-testflight
        bosh_target: {{bosh-lite-target}}
        bosh_username: {{bosh-lite-username}}
        bosh_password: {{bosh-lite-password}}
        bosh_syslog_host: {{bosh-lite-syslog-host}}
        bosh_syslog_port: {{bosh-lite-syslog-port}}
  - put: lite-deployment
    params:
      manifest: manifest/manifest.yml
      stemcells: []
      releases:
        - etcd/*.tgz
        - remote-syslog/*.tgz

- name: shipit
  public: true
  plan:
  - aggregate:
    - {get: boshrelease, passed: [testflight]}
    - {get: boshrelease-ci}
    - {get: candidate-release, passed: [testflight]}
    - {get: version, passed: [testflight], params: {bump: final}}
  - task: create-final-release
    file: boshrelease-ci/ci/tasks/finalize-release.yml
    config:
      params:
        aws_access_key_id: {{cfcommunity-aws-access}}
        aws_secret_access_key: {{cfcommunity-aws-secret}}
  - put: boshrelease
    params:
      repository: final-release-repo
      rebase: true

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/number}

- name: rc
  public: true
  serial_groups: [version]
  plan:
  - {get: boshrelease, trigger: true}
  - get: version
    params: {pre: rc}
  - put: version
    params: {file: version/number}

- name: build-task-image
  serial: true
  plan:
  - {get: boshrelease-ci-task, trigger: true}
  - put: docker-image-ci
    params:
      build: boshrelease-ci-task/ci/ci_image

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: boshrelease-ci
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: boshrelease-ci-task
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [ci/ci_image/*]

- name: boshrelease-pg95-image
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [images/postgresql95-patroni]

- name: boshrelease-pg95-base-image
  type: git
  source:
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [images/postgresql95-patroni-base]

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:drnic/patroni-docker-boshrelease.git
    branch: version
    file: version
    private_key: {{github-private-key}}

- name: final-release
  type: s3
  source:
    bucket: patroni-docker-releases
    regexp: patroni-docker-(.*).tgz
    access_key_id: {{dingotiles-aws-access}}
    secret_access_key: {{dingotiles-aws-secret}}
    region_name: {{dingotiles-aws-region}}

- name: candidate-release
  type: s3
  source:
    bucket: patroni-docker-release-candidates
    regexp: patroni-docker-(.*).tgz
    access_key_id: {{dingotiles-aws-access}}
    secret_access_key: {{dingotiles-aws-secret}}
    region_name: {{dingotiles-aws-region}}

- name: patched-patroni
  type: git
  source:
    uri: https://github.com/drnic/patroni.git
    branch: connect_address
    # uri: https://github.com/zalando/patroni.git
    # branch: master
    private_key: {{github-private-key}}

- name: docker-image-pg95-patroni-base
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql-patroni-base
    tag: "9.5"

- name: docker-image-pg95-patroni
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql-patroni
    tag: "9.5"

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/patroni-docker-boshrelease-pipeline

- name: lite-deployment
  type: bosh-deployment
  source: &lite-defaults
    target: {{bosh-lite-target}}
    username: admin
    password: admin
    deployment: patroni-docker-testflight

- name: etcd
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release

- name: remote-syslog
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/simple-remote-syslog-boshrelease
