---
groups:
- name: pipeline
  jobs: [image-patroni-pg94]
jobs:
- name: image-patroni-pg94-base
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease}
  - put: docker-image-pg94-patroni-base
    params:
      build: boshrelease/images/postgresql94-patroni-base

- name: image-patroni-pg94
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: patroni}
    - {get: boshrelease}
    - {get: boshrelease-images, trigger: true}
  - task: prepare-dockerfile
    file: boshrelease/ci/tasks/prepare-dockerfile.yml
    config:
      params:
        dockerfile_root: boshrelease/images/postgresql94-patroni
  - put: docker-image-pg94-patroni
    params:
      build: prepare-dockerfile/boshrelease/images/postgresql94-patroni

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/patroni-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}

- name: boshrelease-images
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/patroni-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/*]

- name: patroni
  type: git
  source:
    uri: https://github.com/zalando/patroni.git
    branch: master
    private_key: {{github-key}}

- name: docker-image-pg94-patroni-base
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql-patroni-base
    tag: "9.4"

- name: docker-image-pg94-patroni
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/postgresql-patroni
    tag: "9.4"
